# Generated by Django 5.0.4 on 2024-06-24 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.base')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('final_datetime', models.DateTimeField(blank=True, null=True)),
                ('initial_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('chat.base',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.base')),
                ('username', models.CharField(max_length=15, unique=True)),
            ],
            bases=('chat.base',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.base')),
                ('content', models.CharField(max_length=1000)),
                ('datetime_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
            bases=('chat.base',),
        ),
    ]
