# Generated by Django 5.0.3 on 2024-06-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_user_email_remove_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='base',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
