# Generated by Django 5.0.4 on 2024-08-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_img_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img_base64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
